add_newline = false

[username]
style_root = "red bold"
format = "[âš ï¸  user: $user âš ï¸ ]($style) "
disabled = false

[nodejs]
symbol = "ğŸš€ "

[golang]
disabled = true

[aws]
disabled = false
format = 'on [$symbol$profile]($style) '

[gcloud]
disabled = false
format = '| [$active]($style) '

[docker_context]
disabled = true

[kubernetes]
disabled = false

[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_(?P<var_project>[\w-]+)_.*_(?P<var_cluster>[\w-]+)' = '$var_project|$var_cluster'

